expt_name: "dart_CF"
# expt_name: "Hayden"
# expt_name: "Yassour"
# expt_name: "Kostic"
# expt_name: "Vatanen"
# expt_name: "TEDDY"
# expt_name: "Li"

#Input directories, where the fastq sequencing files are stored
indir: "/dartfs/rc/lab/R/RossB/DartCF_infant_meta/ReadData/"
# indir: "/dartfs/rc/lab/R/RossB/OtherLabsPublished/Hayden2020/ReadData/"
# indir: "/dartfs/rc/lab/R/RossB/OtherLabsPublished/Yassour2016/ReadData/"
# indir: "/dartfs/rc/lab/R/RossB/OtherLabsPublished/Kostic2015/ReadData/"
# indir: "/dartfs/rc/lab/R/RossB/OtherLabsPublished/Vatanen2016/ReadData/"
# indir: "/dartfs/rc/lab/R/RossB/OtherLabsPublished/TEDDY/ReadData/"
# indir: "/dartfs/rc/lab/R/RossB/OtherLabsPublished/Li2021/ReadData/"

#Output directories, where files are to be stored
outdir: "/dartfs/rc/lab/R/RossB/DartCF_infant_meta/Results/"
# outdir: "/dartfs/rc/lab/R/RossB/OtherLabsPublished/Hayden2020/Results/"
# outdir: "/dartfs/rc/lab/R/RossB/OtherLabsPublished/Yassour2016/Results/"
# outdir: "/dartfs/rc/lab/R/RossB/OtherLabsPublished/Kostic2015/Results/"
# outdir: "/dartfs/rc/lab/R/RossB/OtherLabsPublished/Vatanen2016/Results/"
# outdir: "/dartfs/rc/lab/R/RossB/OtherLabsPublished/TEDDY/Results/"
# outdir: "/dartfs/rc/lab/R/RossB/OtherLabsPublished/Li2021/Results/"

samples_sub:

samples_ignore:

samples_dir_regex: #If you put something in here, like SRS[0-9]+, it will use that regex to find the sample directories

original_files_R1_identifier: ".1." #"_R1" #Uses this to identify the original R1 files and makes a link. Assumes we can change 1->2 to get the R2

#Quality trimming options
qtrim: "rl" #Trim both sides
quality: 12 #Trim bases below this quality score
quality_read: 12 #Feature counts will ignore reads below this quality score
read_min_len: 20 #Exclude reads below this length
adaptors: '/dartfs/rc/lab/R/RossB/SalernoP/shotgun_metagenomics/Data/adapters.fa' #Path to the adaptors that are trimmed by bbduk
human_genome: '/dartfs/rc/lab/R/RossB/SalernoP/shotgun_metagenomics/Data/hg19.fa.masked' #Path to the reference human genome used to remove human dna contamination

# Bowtie options
n_mismatch: 1
DB_name: "BFT"
DB_path: "/dartfs/rc/lab/R/RossB/SalernoP/shotgun_metagenomics/Data/BFT_isoforms.fasta"

n_cores: 4

# Metaphlan
read_min_len: 30
metaphlan_mode: "rel_ab_w_read_stats" # Default is rel_ab. rel_ab_w_read_stats will include read counts so its generally better
#metaphlan_col: "estimated_number_of_reads_from_the_clade" # Default is relative_abundance. Use estimated_number_of_reads_from_the_clade if you want the read counts
metaphlan_col: "relative_abundance" # Default is relative_abundance. Use estimated_number_of_reads_from_the_clade if you want the read counts

# Everything
mode: "se"

# Shortbred
markers: "/dartfs/rc/lab/R/RossB/SalernoP/shotgun_metagenomics/Data/shortbred_markers.faa"

#RGI
columns:
  - starting_column: "All Mapped Reads"
    renamed_column: "Mapped_Reads"
#  - starting_column: "Average Percent Coverage"
#    renamed_column: "Avg_Percent_Coverage"
#  - starting_column: "Average Length Coverage (bp)"
#    renamed_column: "Avg_Length_Coverage"
#  - starting_column: "Average MAPQ (Completely Mapped Reads)"
#    renamed_column: "Avg_MAPQ"

# Fasta files to be used for calculating gene lengths, can add any fasta files needed
fasta_files: 
  - "/dartfs/rc/lab/R/RossB/SalernoP/CF_ARG_dynamics/CARD/card_database_v3.2.7_all.fasta"
  - "/dartfs/rc/lab/R/RossB/SalernoP/CF_ARG_dynamics/CARD/wildcard_database_v3.2.7_all.fasta"

# Percent coverage desired for MAG bin refinement and reassembly
coverage: 70
# Percent contamination allowed for MAG bin refinement and reassembly
contamination: 5